name: Magnus Sörensen
url: http://byteofsoren.github.io
description: Robotic programmer

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
