name: Magnus Sörensen (robotic programmer)
url: http://byteofsoren.github.io
description: Magnus Sörensens blog site

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
